version: "3.9"

services:
  web:
    build: .
    container_name: todo_plus_notes_web_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

